server:
  port: 8092
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  ## 这个很重要: 禁用activiti自动扫描processes目录功能,不然会报错启动不了项目
  activiti: 
    check-process-definitions: false    